"use client";

import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Heading, Text } from "@/components/ui/typography";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Grid } from "@/components/layout/grid";
import { Container } from "@/components/layout/container";
import { Section } from "@/components/layout/section";
import { Loader } from "@/components/ui/loader";
import { useToast } from "@/hooks/use-toast";
import { 
  Sparkles, 
  Settings, 
  Brain, 
  Check, 
  Code, 
  BookOpen, 
  ListTodo, 
  ChevronRight,
  ArrowLeft
} from "lucide-react";
import { cn } from "@/lib/utils";

// Simulated AI steps
const generationSteps = [
  "Structuring topic paradigms and cognitive map...",
  "Formulating multiple-choice context arrays...",
  "Drafting algorithmic coding problem statements...",
  "Compiling automatic grading schemas & unit tests...",
  "Assembling visual quiz paper sheet..."
];

export default function CreateAssignmentPage() {
  const router = useRouter();
  const { toast } = useToast();

  // Wizard state parameters
  const [topic, setTopic] = React.useState("");
  const [audience, setAudience] = React.useState("");
  const [difficulty, setDifficulty] = React.useState<"beginner" | "intermediate" | "expert">("intermediate");
  const [questionCount, setQuestionCount] = React.useState<5 | 10 | 20>(10);
  const [selectedTypes, setSelectedTypes] = React.useState<string[]>(["mcq", "coding"]);
  
  // Simulated AI loading state
  const [isGenerating, setIsGenerating] = React.useState(false);
  const [currentStepIdx, setCurrentStepIdx] = React.useState(0);

  const toggleType = (type: string) => {
    if (selectedTypes.includes(type)) {
      if (selectedTypes.length > 1) {
        setSelectedTypes(selectedTypes.filter((t) => t !== type));
      }
    } else {
      setSelectedTypes([...selectedTypes, type]);
    }
  };

  const handleGenerate = () => {
    if (!topic.trim()) {
      toast({
        title: "Configuration Required",
        description: "Please specify a topic or subject for the assessment.",
        variant: "destructive",
      });
      return;
    }

    // Start simulation
    setIsGenerating(true);
    setCurrentStepIdx(0);
  };

  // Timer loop for loading steps simulation
  React.useEffect(() => {
    if (!isGenerating) return;

    if (currentStepIdx < generationSteps.length) {
      const timer = setTimeout(() => {
        setCurrentStepIdx((prev) => prev + 1);
      }, 1500); // 1.5 seconds per step
      return () => clearTimeout(timer);
    } else {
      // Completed, redirect
      setIsGenerating(false);
      toast({
        title: "Assessment Formulated!",
        description: `'${topic}' quiz has been successfully generated by our AI agent.`,
        variant: "success" as any,
      });
      router.push(`/preview/${topic.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`);
    }
  }, [isGenerating, currentStepIdx, topic, router, toast]);

  return (
    <Section size="sm" className="flex-1 flex flex-col pt-6 relative">
      {/* --- AI GENERATION OVERLAY LOADER (Matching premium high-blur mockups) --- */}
      {isGenerating && (
        <div className="fixed inset-0 z-50 bg-black/85 backdrop-blur-xl flex flex-col items-center justify-center p-6 animate-in fade-in duration-300">
          <div className="absolute top-[-20%] left-[-10%] w-[600px] h-[600px] rounded-full bg-veda-purple-500/10 blur-[130px]" />
          <div className="absolute bottom-[-20%] right-[-10%] w-[600px] h-[600px] rounded-full bg-veda-indigo-500/10 blur-[130px]" />

          <div className="max-w-md w-full text-center space-y-8 relative z-10">
            {/* Pulsing visual core container */}
            <div className="relative">
              <div className="absolute inset-0 rounded-3xl bg-gradient-to-tr from-veda-purple-500 to-veda-indigo-500 blur-xl opacity-40 animate-pulse" />
              <div className="relative h-20 w-20 rounded-2xl bg-gradient-to-tr from-veda-purple-500 to-veda-indigo-500 flex items-center justify-center text-white shadow-glow-strong mx-auto animate-bounce duration-1000">
                <Brain className="h-10 w-10 text-white" />
              </div>
            </div>

            <div className="space-y-3">
              <Heading variant="h3" className="text-2xl font-bold text-white tracking-tight">
                Synthesizing Assessment Core
              </Heading>
              <div className="h-8 flex items-center justify-center">
                <Text className="text-xs font-mono text-zinc-300 tracking-wide">
                  {generationSteps[currentStepIdx] || "Formulating output..."}
                </Text>
              </div>
            </div>

            {/* Stepped progress bar */}
            <div className="space-y-2.5">
              <Loader variant="bar" size="md" color="accent" className="h-2 rounded-full bg-zinc-800" />
              <div className="flex justify-between text-[11px] text-zinc-400 font-mono">
                <span className="flex items-center gap-1"><Sparkles className="h-3 w-3 text-accent animate-pulse" /> PHASE {Math.min(currentStepIdx + 1, 5)} OF 5</span>
                <span>{Math.round((Math.min(currentStepIdx, 5) / 5) * 100)}% COMPLETE</span>
              </div>
            </div>
          </div>
        </div>
      )}

      <Container className="space-y-6 flex-1 flex flex-col max-w-4xl">
        {/* Breadcrumb Header */}
        <div className="flex items-center gap-2 text-xs text-muted-foreground font-medium">
          <Link href="/dashboard" className="hover:text-foreground flex items-center gap-1">
            <ArrowLeft className="h-3.5 w-3.5" /> Dashboard
          </Link>
          <ChevronRight className="h-3 w-3" />
          <span className="text-foreground font-semibold">Create Quiz Wizard</span>
        </div>

        <div>
          <Heading variant="h2" as="h1" className="text-2xl font-extrabold sm:text-3xl tracking-tight leading-none">
            Create New Assessment
          </Heading>
          <Text className="text-muted-foreground text-sm mt-1">Configure target subjects, select difficulty metrics, and specify code challenges.</Text>
        </div>

        <Grid cols={1} mdCols={3} gap={6} className="items-start flex-1 mt-2">
          {/* Main config forms */}
          <div className="md:col-span-2 space-y-6">
            <Card glass className="border border-border/40 shadow-md">
              <CardHeader className="p-6">
                <CardTitle className="text-base flex items-center gap-2 font-bold">
                  <Settings className="h-5 w-5 text-primary" />
                  Subject Matter Parameters
                </CardTitle>
                <CardDescription className="text-xs">Specify what target parameters drive the question generation algorithms.</CardDescription>
              </CardHeader>
              <CardContent className="p-6 pt-0 space-y-5">
                <div className="space-y-2">
                  <label className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest block">Select a subject / topic</label>
                  <Input 
                    type="text" 
                    placeholder="e.g. React Server Components, CSS Flexbox, Node.js Streams..." 
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    className="focus:ring-2 focus:ring-primary/20 focus:border-primary/60 transition-all duration-200"
                  />
                </div>

                <div className="space-y-2">
                  <label className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest block">Target Audience Profile</label>
                  <Input 
                    type="text" 
                    placeholder="e.g. Junior Frontend Dev, Senior Cloud Engineer..." 
                    value={audience}
                    onChange={(e) => setAudience(e.target.value)}
                    className="focus:ring-2 focus:ring-primary/20 focus:border-primary/60 transition-all duration-200"
                  />
                </div>
              </CardContent>
            </Card>

            {/* Question formats */}
            <Card glass className="border border-border/40 shadow-md">
              <CardHeader className="p-6">
                <CardTitle className="text-base flex items-center gap-2 font-bold">
                  <ListTodo className="h-5 w-5 text-accent" />
                  Question Format Options
                </CardTitle>
                <CardDescription className="text-xs">Select what formats represent the drafted test sheets.</CardDescription>
              </CardHeader>
              <CardContent className="p-6 pt-0 grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div 
                  onClick={() => toggleType("mcq")}
                  className={cn(
                    "p-4 rounded-xl border flex items-center justify-between cursor-pointer transition-all duration-200 select-none",
                    selectedTypes.includes("mcq")
                      ? "bg-primary/10 border-primary text-foreground shadow-sm font-semibold"
                      : "bg-muted/5 border-border hover:bg-muted/20 text-muted-foreground"
                  )}
                >
                  <span className="flex items-center gap-2.5 text-xs">
                    <BookOpen className={cn("h-4.5 w-4.5 shrink-0", selectedTypes.includes("mcq") ? "text-primary" : "text-muted-foreground")} /> 
                    Multiple Choice (MCQ)
                  </span>
                  <div className={cn(
                    "h-5 w-5 rounded border flex items-center justify-center shrink-0 transition-colors",
                    selectedTypes.includes("mcq") ? "border-primary bg-primary text-primary-foreground" : "border-muted-foreground/30"
                  )}>
                    {selectedTypes.includes("mcq") && <Check className="h-3.5 w-3.5 stroke-[3]" />}
                  </div>
                </div>

                <div 
                  onClick={() => toggleType("coding")}
                  className={cn(
                    "p-4 rounded-xl border flex items-center justify-between cursor-pointer transition-all duration-200 select-none",
                    selectedTypes.includes("coding")
                      ? "bg-accent/10 border-accent text-foreground shadow-sm font-semibold"
                      : "bg-muted/5 border-border hover:bg-muted/20 text-muted-foreground"
                  )}
                >
                  <span className="flex items-center gap-2.5 text-xs">
                    <Code className={cn("h-4.5 w-4.5 shrink-0", selectedTypes.includes("coding") ? "text-accent" : "text-muted-foreground")} /> 
                    Coding Challenges
                  </span>
                  <div className={cn(
                    "h-5 w-5 rounded border flex items-center justify-center shrink-0 transition-colors",
                    selectedTypes.includes("coding") ? "border-accent bg-accent text-accent-foreground" : "border-muted-foreground/30"
                  )}>
                    {selectedTypes.includes("coding") && <Check className="h-3.5 w-3.5 stroke-[3]" />}
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Right sidebar presets */}
          <div className="space-y-6">
            <Card glass className="border border-border/40 shadow-md">
              <CardHeader className="p-5">
                <CardTitle className="text-base font-bold">Difficulty Preset</CardTitle>
              </CardHeader>
              <CardContent className="p-5 pt-0 space-y-3">
                <div 
                  onClick={() => setDifficulty("beginner")}
                  className={cn(
                    "p-3.5 rounded-xl border cursor-pointer transition-all duration-200 select-none text-xs font-semibold flex items-center justify-between",
                    difficulty === "beginner"
                      ? "border-emerald-500 bg-emerald-500/10 text-emerald-800 dark:text-emerald-300 shadow-sm"
                      : "border-border/60 hover:bg-muted/20 text-muted-foreground"
                  )}
                >
                  <span>Beginner Core</span>
                  {difficulty === "beginner" && <div className="h-2 w-2 rounded-full bg-emerald-500" />}
                </div>
                
                <div 
                  onClick={() => setDifficulty("intermediate")}
                  className={cn(
                    "p-3.5 rounded-xl border cursor-pointer transition-all duration-200 select-none text-xs font-semibold flex items-center justify-between",
                    difficulty === "intermediate"
                      ? "border-primary bg-primary/10 text-primary shadow-sm"
                      : "border-border/60 hover:bg-muted/20 text-muted-foreground"
                  )}
                >
                  <span>Intermediate Applied</span>
                  {difficulty === "intermediate" && <div className="h-2 w-2 rounded-full bg-primary" />}
                </div>

                <div 
                  onClick={() => setDifficulty("expert")}
                  className={cn(
                    "p-3.5 rounded-xl border cursor-pointer transition-all duration-200 select-none text-xs font-semibold flex items-center justify-between",
                    difficulty === "expert"
                      ? "border-amber-500 bg-amber-500/10 text-amber-800 dark:text-amber-300 shadow-sm"
                      : "border-border/60 hover:bg-muted/20 text-muted-foreground"
                  )}
                >
                  <span>Expert Technical</span>
                  {difficulty === "expert" && <div className="h-2 w-2 rounded-full bg-amber-500" />}
                </div>
              </CardContent>
            </Card>

            {/* Questions count */}
            <Card glass className="border border-border/40 shadow-md">
              <CardHeader className="p-5">
                <CardTitle className="text-base font-bold">Questions Count</CardTitle>
              </CardHeader>
              <CardContent className="p-5 pt-0">
                <div className="grid grid-cols-3 gap-2 bg-muted/20 p-1.5 rounded-xl border border-border/40">
                  {[5, 10, 20].map((count) => (
                    <div
                      key={count}
                      onClick={() => setQuestionCount(count as any)}
                      className={cn(
                        "py-2.5 rounded-lg text-center cursor-pointer transition-all duration-200 select-none text-xs font-bold",
                        questionCount === count
                          ? "bg-background border border-border/40 text-foreground shadow-sm"
                          : "hover:bg-muted/30 text-muted-foreground"
                      )}
                    >
                      {count}
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            <Button 
              variant="gradient" 
              size="lg" 
              className="w-full py-6 rounded-xl shadow-glow-strong text-sm font-bold active:scale-[0.98] transition-transform duration-100"
              onClick={handleGenerate}
            >
              <Sparkles className="h-4.5 w-4.5 mr-2 animate-pulse" /> Start AI Formulation
            </Button>
          </div>
        </Grid>
      </Container>
    </Section>
  );
}
